### ISSUE TITLE
Crash at server start

### ISSUE THREAD

**Issue by DavidSarif** [Krutoy242/Enigmatica2Expert-Extended#218]
## Description

After update to 1.5.0 from 1.4.0 can't start the single player server. Crash reports from two last tries attached.

**To Reproduce**

1. Try to load saved world.
2. See error.

**Modpack version** `v1.5.0`

**`debug.log` or Crash report**

[crash-2023-05-26_21.59.22-client.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11579242/crash-2023-05-26_21.59.22-client.txt)
[crash-2023-05-26_22.22.45-client.txt](https://github.com/Krutoy242/Enigmatica2Expert-Extended/files/11579243/crash-2023-05-26_22.22.45-client.txt)

**Comment by DavidSarif** [comment]
The same save works well in modpack v1.4.0

**Comment by Krutoy242** [comment]
Thank you for the report! I will investigate the issue.

**Comment by Krutoy242** [comment]
Try to remove `CensoredASM` mod and see if problem persist

**Comment by DavidSarif** [comment]
Removed CensoredASM mod: the game works as usual.

**Comment by Krutoy242** [comment]
Seems like this is result of latest CensoredASM updates. You can try to download latest, even newer version of CensoredASM from CurseForge and try start with it. There was patch version, maybe big was fixed.

If this won't help, try to downgrade mod to version that was on 1.4.0

**Comment by DavidSarif** [comment]
https://github.com/LoliKingdom/LoliASM/issues/169#issue-1724107052

Fixed in CensoredASM version 5.10 .

**Comment by DavidSarif** [comment]
Checked modpack version 1.6.0 : CensoredASM is 5.10, but the issue is still the same. Downgrade is the only option for now.

**Comment by Krutoy242** [comment]
Could you mention this in that issue tread then, back to LoliASM? https://github.com/LoliKingdom/LoliASM/issues/169

**Comment by Krutoy242** [comment]
Downgraded LoliASM version for modpack to fix that.
